name: Build and Generate Executable

on:
  push:
    branches:
      - main  # 在主分支推送代码时触发
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装依赖项
    - name: Setup VTK and ITK
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install vtk itkwrapper -y

    # 配置和编译项目
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DVTK_BUILD_SHARED_LIBS=OFF -DITK_BUILD_SHARED_LIBS=OFF ..
        cmake --build . --config Release

    # 打包生成的可执行文件
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 3DVoronoiExecutable
        path: build/Release/3DVoronoiAssignment.exe
